#!/bin/bash
# srt.sh: Sharad Build Tool

. srt-usage
. srt-publish
. srt-install

case $1 in

        publish)
                echo "Publishing sharad server"
                shift
                srt-publish $@
                ;;

        install)
                echo "Installing sharad server"
                shift
                srt-install $@
                ;;

        *)
                echo "Unknown command $1" >&2
                usage
                exit 1
                ;;
esac
