#!/bin/bash
# srt-publish.sh

srt-publish() {
    case $1 in
            --input)
                    shift
                     if [[ -z $1 ]]; then
                             echo "--input needs an argument" >&2
                             exit 1
                     fi
                     repo_dir=$HOME/.local/share/srt/sharad-backend/
                     artifact=$1
                     mkdir -p $repo_dir
                     echo "Copying $artifact into $repo_dir"
                     cp "$artifact" "$repo_dir"
                     ;;
            *)
                     echo "--input is necessary for srt to publish it" >&2
                     exit 1
                     ;;
    esac
}
