#!/bin/bash
# srt-install.sh

srt-install() {
    if [[ ! $1 == "--to" ]]; then
            echo "--to is necessary for sbr to install sharad-backend" >&2
            exit 1
    fi
    shift
    if [[ -z $1 ]]; then
            echo "--to needs an argument" >&2
            exit 1
    fi
    to=$1
    echo "installing sharad backend to $to"
    cp "$HOME/.local/share/srt/sharad-backend/sharad-backend" $to
}
