#!/bin/bash
# srt-usage.sh

srt-usage() {
    cat <<EOF
USAGE: srt [COMMAND] [OPTIONS]

The Sharad Build Tool enables smooth integration of the underlying build tool (i.e cabal in this setting)
with the rest of the sharad ecosystem (e.g. 'sharad.sh', the wrapper around the sharad server and 'srt' the Sharad Repository Tool)

Options:
  -h    Displays this usage

Commands:
  publish    Builds the sharad server then Publishes it into the Sharad Repository
  install    Installs the wanted version of sharad-backend into the desired directory.
             Example: srt install --to .
             installs the latest version of the sharad backend into the current directory
EOF
}

