#!/bin/bash
# srt-publish.sh

srt-publish() {
    if [[ ! $1 == "--input" ]]; then
            echo "--input is necessary for sbr to publish it" >&2
            exit 1
    fi
    shift
    if [[ -z $1 ]]; then
            echo "--input needs an argument" >&2
            exit 1
    fi
    repo_dir=$HOME/.local/share/srt/sharad-backend/
    artifact=$1
    mkdir -p $repo_dir
    cp $artifact $repo_dir
}
